list=[1,2,3,4,5]

#1.Append Method
list.append(10)
print(list)
o/p: [1,2,3,4,5,10]

#2.clear Method
list.clear()
o/p: []

#3.copy()-returns the copy of the list
x=[1,2,3,4,5,10]
x=list.copy()
print(x)
o/p:[1,2,3,4,5,10]

#4.count()-counts the occurences of specified element
l=[1,1,1,2,3,4,2,3]
l.count(1)   #3
l.count(2)   #2
l.count('a') #0

#5.pop()-will remove last element
l=[1,1,1,2,3,4,2,3]
print(l.pop())    #3
print(l.pop())    #2
print(l)          #[1,1,1,2,3,4]

print(l.pop(0))  #1
print(l)         #[1,1,2,3,4]

#6.reverse()-
l=[1,4,2,7,3]
l.reverse()
print(l)    #[3,7,2,4,1]

#7.sort()-sorts the list in ascending order
l.sort()
print(l)   #[1,2,3,4,7]

l.sort(reverse=True)  - sorts the list in decreasing order
print(l)   #[7,4,3,2,1]

#8.remove()-removes the specified element
l3=[1,2,2,3,4,5]
l3.remove(2)
print(l3)      #[1,2,3,4,5]

#9.insert()-adds the element at the specified position
l3.insert()


#patterns
         *
       * * *
     * * * * *
   
   
   
Errors and Exceptions
 what? why? at what time?
 
 errors are of two types
 1.logical errors-come into existence at runtime
 2.syntax errors-come into existence at compile time
 
 Exception-
 1.stmt
 2.1/0 -exception always come into existence at runtime
 3.stmt
 
 1.ZeroDivisionError
 print(1/0)
 o/p: ZeroDivisionError:division by zero
 Syntax error is also an exception
 print["hello world"]
 o/p: TypeError:'byiltin_function_or_method' is not
 
 EOFError-when input reaches end of the file
 
 IndexError-when we access index that doesn't exists
 l=[1,2,3,4]
 print(l[6])
 IndexError:list index out of range
 
 ImportError
 
 KeyboardInterrupt
 
 RuntimeError
 
 ValueError
 
 NameError
 
 IndentationError
 
 Exception Handling
 try: 
   x=23/0
 except:
   print("Execution occured")
o/p: execution occured

 try: 
   x=1/0
 except ZeroDivisionError:
   print("ZeroDivisionError occured")
o/p:ZeroDivisionError occured

Try with Multiple catch:
try:
 x=1/0
except EOFError:
 print("end of the file occured")
except ImportError:
 print("import error exception occured")
except ZeroDivisionError:
 print("ZeroDivisionError occured")
 o/p:ZeroDivisionError occured
 
 
Try with else: else will be executed after try when there is no exception
try:
 x=1/10
except EOFError:
 print("end of the file occured")
except ImportError:
 print("import error exception occured")
except ZeroDivisionError:
 print("ZeroDivisionError occured")
else:
 print("control is inside else")
 o/p:control is inside else
 
try:
 x=1/10
 print("inside try")
except EOFError:
 print("end of the file occured")
except ImportError:
 print("import error exception occured")
except ZeroDivisionError:
 print("ZeroDivisionError occured")
else:
 print("control is inside else")
 o/p:
 inside try
 control is inside else
 
 try:
 x=1/0
except EOFError:
 print("end of the file occured")
except ImportError:
 print("import error exception occured")
except ZeroDivisionError:
 print("ZeroDivisionError occured")
else:
 print("control is inside else")
 o/p:ZerodivisionError
 
try:
 x=1/0
except ZeroDivisionError as err:
 
 
